#spring:
#  application:
#    name: eureka-server
#
#---
#spring:
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://peer2:8761/eureka/      # 将自己注册到peer2这个Eureka上面去
#  server:
#    enable-self-preservation: false
#
#---
#spring:
#  profiles: peer2
#server:
#  port: 8761
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: peer2
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/
#  server:
#    enable-self-preservation: false
#
